apiVersion: v1
kind: Service
metadata:
    name: kubernetes-users
    namespace: kube-system
    labels:
        k8s-app: kubernetes-users
        kubernetes.io/cluster-service: "true"
        addonmanager.kubernetes.io/mode: Reconcile
spec:
    type: NodePort 
    selector:
        k8s-app: kubernetes-users
    ports:
    - port: 80  # service port
      targetPort: 8030 # container port
      nodePort: 32019 # node port
