apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: kubernetes-users
    namespace: kube-system
    labels:
        k8s-app: kubernetes-users
        kubernetes.io/cluster-service: "true"
spec:
    selector:
        matchLabels:
            k8s-app: kubernetes-users
    template:
        metadata:
            labels:
                k8s-app: kubernetes-users
        spec:
            nodeName: 0c-c4-7a-15-e1-9c
            containers:
              - name: kubernetes-users
                image: bootstrapper:5000/zhanghui/k8s-users
                ports:
                - containerPort: 8030
                  protocol: TCP
                env:
                 - name: ABAC_POLICY_FILE
                   value: /etc/kubernetes/abac/policy.jsonl
                 - name: ROOT_CA_CERT 
                   value: /etc/kubernetes/ssl/ca.pem
                 - name: ROOT_CA_KEY
                   value: /etc/kubernetes/ssl/ca-key.pem
                 - name: SMTP_SVC_ADDR 
                   value: "smtp.partner.outlook.cn:587" 
                 - name: ADMIN_EMAIL 
                   value: "admin@unisound.com" 
                 - name: ADMIN_SECRT 
                   value: "...." 
                 - name:  ADDR 
                   value: ":8030" 
                volumeMounts:
                - name: docker-sock 
                  mountPath: /var/run
                - name: kube-config
                  mountPath: /etc/kubernetes
            volumes: 
             - name: kube-config 
               hostPath:
                  path:  /etc/kubernetes
             - name: docker-sock
               hostPath:
                  path:  /var/run

