apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: kubernetes-users
    namespace: kube-system
    labels:
        k8s-app: kubernetes-users
        kubernetes.io/cluster-service: "true"
        addonmanager.kubernetes.io/mode: Reconcile
spec:
    selector:
        matchLabels:
            k8s-app: kubernetes-users
    template:
        metadata:
            labels:
                k8s-app: kubernetes-users
            annotations:
                scheduler.alpha.kubernetes.io/critical-pod: ''
        spec:
            containers:
              - name: kubernetes-users
                image: zh794390558/k8s-users
                resources:
                    limits:
                        cpu: 100m
                        memory: 20Mi
                    requests:
                        cpu: 100m
                        memory: 20Mi
                ports:
                - containerPort: 80
                env:
                 - name: ABAC_POLICY_FILE
                   value: /etc/kubernetes/abac/policy.jsonl
                 - name: ROOT_CA_CERT 
                   value: /etc/kubernetes/ssl/ca.pem
                 - name: ROOT_CA_KEY
                   value: /etc/kubernetes/ssl/ca-key.pem
                 - name: SMTP_SVC_ADDR 
                   value: "smtp.partner.outlook.cn:587" 
                 - name: ADMIN_EMAIL 
                   value: "zhanghui@unisound.com" 
                 - name: ADMIN_SECRT 
                   value: "zh...1234" 
                 - name:  ADDR 
                   value: ":80" 
                volumeMounts:
                - name: ssl-ca
                  readOnly: true
                  mountPath: /etc/ssl/certs
                - name: docker-sock 
                  mountPath: /var/run
            volumes: 
             - name: ssl-ca
               hostPath:
                  path:  /etc/ssl/certs
             - name: docker-sock
               hostPath:
                  path:  /var/run

